### ISSUE TITLE
Node-Red

### ISSUE THREAD

**Issue by riddertommie** [home-assistant/hassio-build#122]
I don't know if this is the right starting point.

Hi if have problems with installing new node red plugin. At first it works but after a curtain time its going into a error loop, i tried the stable and the beta version off hassio.  

I also have a RPI whit hassio and there is no problem with that.

logfile below line

----------------------------

[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Node-RED v1.1.0

 Flow-based programming for the Internet of Things

 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 

INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-warning.sh: executing... 
WARNING: No users configured and authentication has been disabled!
WARNING: This is not recommended!!!
[cont-init.d] 11-warning.sh: exited 0.
[cont-init.d] 20-config.sh: executing... 
[cont-init.d] 20-config.sh: exited 0.
[cont-init.d] 80-system-packages.sh: executing... 
[cont-init.d] 80-system-packages.sh: exited 0.
[cont-init.d] 81-npm-packages.sh: executing... 
[cont-init.d] 81-npm-packages.sh: exited 0.
[cont-init.d] 82-user-scripts.sh: executing... 
[cont-init.d] 82-user-scripts.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

> hassio-addon-node-red@1.0.0 start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

Error loading settings file: /etc/node-red/config.js
TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/etc/node-red/config.js:27:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/node_modules/node-red/red.js:115:20)
    at Module._compile (module.js:635:30)

> hassio-addon-node-red@1.0.0 start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

Error loading settings file: /etc/node-red/config.js
TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/etc/node-red/config.js:27:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/node_modules/node-red/red.js:115:20)

**Comment by riddertommie** [comment]
sorry for the stupid writing mistake.......

**Comment by pvizeli** [comment]
That is what you search for: https://github.com/hassio-addons/addon-node-red
