### ISSUE TITLE
Problems fresh Install (zeroconf)

### ISSUE THREAD

**Issue by riddertommie** [home-assistant/hassio-build#153]
Hi All.

I did a fresh install via > 

https://github.com/home-assistant/hassio-build/blob/master/install/hassio_install

and now getting following error 

2019-04-03 12:49:57 ERROR (MainThread) [homeassistant.setup] Error during setup of component zeroconf,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component,
    component.setup, hass, processed_config)  # type: ignore,
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zeroconf/__init__.py", line 29, in setup,
    zeroconf = Zeroconf(),
  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 1734, in __init__,
    socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value),
OSError: [Errno 105] No buffer space available,
2019-04-03 12:49:57 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.0 seconds.,

This looks a little like:

https://github.com/home-assistant/home-assistant/issues/22422

wich is referred to:

https://github.com/tchellomello/raincloudy/issues/30

It's a fresh install, im on Ubuntu 18.10 with docker hassio is versio 152.

Any help is appreciated

**Comment by pvizeli** [comment]
> `OSError: [Errno 105] No buffer space available,`

That means your system has not enough space for sockets. Maybe a HassOS inside a VM would be a better solution for you, so you need not to fight with your operating system.
